# Generated by Django 2.0.2 on 2018-02-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecentStockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=25)),
                ('ticker', models.CharField(max_length=25)),
                ('industry', models.CharField(max_length=25)),
                ('sector', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserStockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='schema.Users')),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='userstockdata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Users'),
        ),
        migrations.AddField(
            model_name='recentstockdata',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Stocks'),
        ),
        migrations.AddField(
            model_name='historicalstockdata',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Stocks'),
        ),
        migrations.AlterUniqueTogether(
            name='userstockdata',
            unique_together={('user_id', 'stock_id')},
        ),
        migrations.AlterUniqueTogether(
            name='recentstockdata',
            unique_together={('stock_id', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='historicalstockdata',
            unique_together={('stock_id', 'date')},
        ),
    ]
