# Generated by Django 2.0.2 on 2018-02-27 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20180226_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockdata',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Stocks'),
        ),
        migrations.AlterField(
            model_name='password',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='schema.Users'),
        ),
        migrations.AlterField(
            model_name='recentstockdata',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Stocks'),
        ),
        migrations.AlterField(
            model_name='userstockdata',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Stocks'),
        ),
        migrations.AlterField(
            model_name='userstockdata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalstockdata',
            unique_together=set(),
        ),
    ]
